### ISSUE TITLE
Unable to capture Transparent Renders with Lagarith or MagicYUV

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProMovieCapture#169] opened 2022-05-13 09:21 UTC
The original issue has been resolved. 

Thank you!

Unfortunately, I'm now having trouble over on the Windows side, where I'm also trying to get Transparent video capture working.  

- I am trying to use either Lagarith or MagicYUV to capture Transparent video on Windows.

- I have installed and configured both of those compression encoders on my computer.

- AVPro MovieCapture finds both Lagarith and MagicYUV and lists them in the list of available encoders.  

- However, when I set it to use either of them, I get the error at runtime:
`Failed to create recorder`

UPDATE - At the end of the day, I just tried using the codecs with the repro project you had sent, and I got the repro to encode with both plugins.  However, the videos won't import into any video editors I have available or the Mac version of After Effects.  

- Maybe this is technically still working how you had intended it though - so I won't create a new issue yet.  
   Still no idea why the codecs won't work so far with my app.

- If you have any general advice for creating transparent videos on Windows with MovieCapture, I'd appreciate it...

Thank you

_Originally posted by @pnostudiodeveloper in https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/165#issuecomment-1125504514_

**Comment by AndrewRH** [comment] 2022-05-13 12:23
@pnostudiodeveloper 
Hmm Lagarith and MagicYUV should both work once you've configured them...They need to output to AVI files.
Perhaps you could share here a short video capture that's not opening so we can take a look?
Thanks,

**Comment by pnostudiodeveloper** [comment] 2022-05-13 17:17
Here are the Lagarith and MagicYUV captures from the repro project on Windows.

It seems they do open in After Effects 2015 on Windows - however, the background shows as solid green and doesn't seem to be transparent.

https://www.dropbox.com/s/y10dwl4wpho79ov/Lagarith.avi?dl=1

https://www.dropbox.com/s/ka8e8qbn36bmhao/MagicYUV.avi?dl=1


- Note:  I am using the Free version of MagicYUV from magicyuv.com - version 1.2-rev2

**Comment by AndrewRH** [comment] 2022-05-16 09:00
@pnostudiodeveloper ⬆️ 😄

**Comment by pnostudiodeveloper** [comment] 2022-05-16 15:29
Thank you!

I can get both codecs to render transparent now.

Hopefully I'll be able to get the codecs to work in my app today.

- I can see you provided access to the codec Configure panel from inside the AVPro plugin.  Is there any way for me to provide users with access to that Configure panel from inside my app?  
I'm worried that trying to get them to find a way to access the Configure panel for the codec could be challenging.

**Comment by pnostudiodeveloper** [comment] 2022-05-16 20:42
Unfortunately, there does seem to be an issue with selecting either Lagarith or MagicYUV at runtime using NativeForceVideoCodecIndex.

Here is a repro project.  Please open "SampleScene.unity"
[https://www.dropbox.com/s/sz7zgfn7946ougj/Lagarith%20Debug.zip?dl=1](url)

1.  If you run it as is, it will replicate the error - capture does not start after trying to force Lagarith as the codec at runtime with NativeForceVideoCodecIndex before calling StartCapture()

2.  If you switch the Video Codec Priority in the GUI of the CaptureFromCamera component in the editor so that Lagarith is at the top of the list, the capture runs perfectly without any error.


This suggests that the framework doesn't like being forced to use Lagarith or MagicYUV at runtime.  

I need to give my users a choice of codec at runtime, as the majority will prefer H.264, but some need these third party formats for transparent renders.


I hope this repro makes it easier to replicate and solve the issue.

Thank you

**Comment by AndrewRH** [comment] 2022-05-17 11:56
Original comment: 
Unfortunately, there does seem to be an issue with selecting either Lagarith or MagicYUV at runtime using NativeForceVideoCodecIndex.

Here is a repro project. Please open "SampleScene.unity"
[attached]

If you run it as is, it will replicate the error - capture does not start after trying to force Lagarith as the codec at runtime with NativeForceVideoCodecIndex before calling StartCapture()

If you switch the Video Codec Priority in the GUI of the CaptureFromCamera component in the editor so that Lagarith is at the top of the list, the capture runs perfectly without any error.

This suggests that the framework doesn't like being forced to use Lagarith or MagicYUV at runtime.

I need to give my users a choice of codec at runtime, as the majority will prefer H.264, but some need these third party formats for transparent renders.

I hope this repro makes it easier to replicate and solve the issue.

Thank you

**Comment by AndrewRH** [comment] 2022-05-17 12:07
I believe the issue is caused by the file extension being MP4 instead of AVI.  Actually our script is meant to automatically switch to AVI but it's not working.

I've attached an updated script here which should solve it.  Please replace the existing CaptureBase.cs file in /Plugins/RenderHeds/AVProMovieCapture/Runtime/Scripts/Internal with this one:

[CaptureBase.cs.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/8708045/CaptureBase.cs.zip)

Thanks,

**Comment by AndrewRH** [comment] 2022-05-17 12:08
And for MagicYUV this code should work:

`		foreach (Codec codec in CodecManager.VideoCodecs)
		{
			if (codec.Name.StartsWith("MagicYUV lossless"))
			{
				captureFromCamera.NativeForceVideoCodecIndex = codec.Index;
				break;
			}
		}`

**Comment by AndrewRH** [comment] 2022-05-19 12:50
@pnostudiodeveloper  does that help?

**Comment by pnostudiodeveloper** [comment] 2022-05-19 15:40
Yes that helps!  

Sorry, had other work and couldn't look at this last two days.

I think this means everything is currently resolved.  

I can't imagine there will be any other issues with doing transparent renders, but at this point, I'll keep my fingers crossed and knock on wood....

**Comment by pnostudiodeveloper** [comment] 2022-05-19 15:48
One last unrelated but important question:

- I manually set the Bitrate on H.264 captures to give users control over quality.   "Medium", "High", "Best" modes in my app all equal different precalculated hardcoded bitrates being set on CaptureFromCamera.

- As I've been expanding the formats available to the user past H.264 this week to include Apple ProRes, I noticed that the bitrate control doesn't seem to apply to ProRes.  It seems like it's just going ahead with whatever bitrate ProRes usually uses - which is perfect in that case, because it's essentially used like a lossless format.

- Just wondering - can you include in the documentation which formats are affected by the Bitrate setting, and which are not?  Here are the additional formats I'm wondering how the Bitrate setting would affect:
       HEVC
       Lagarith
       MagicYUV

**Comment by Chris-RH** [comment] 2022-05-20 09:56
Thank you @pnostudiodeveloper, we'll look into including that in the documentation.
I'm going to close this as your issue seems to be resolved. Please reopen if you have any further problems with it.

**Closed by Chris-RH** 2022-05-20 09:56 UTC
Labels: windows

**Comment by AndrewRH** [comment] 2022-05-22 16:08
@pnostudiodeveloper 

Yes we'll add that to the documentation.  Bitrate currently only affects H264 and HEVC

ProRes has a fixed bitrate depending on the profile you use.

**Comment by pnostudiodeveloper** [comment] 2022-05-22 16:22
Thank you for the clarification!
