### ISSUE TITLE
[macOS][iOS] Captured video darker using URP and linear color space

### ISSUE THREAD

**Issue by vedran-delta** [RenderHeads/UnityPlugin-AVProMovieCapture#276] opened 2023-04-18 11:29 UTC
**Describe the bug**
When recording a video with CaptureFromCamera or CaptureFromTexture components the captured video is much darker than it should be.
This issue was resolved in the AVPro Movie Capture v.4.7.9 and reintroduced itself in version 5.1.2.

Linked issue:
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/156

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.35f1
 - AVPro Movie Capture version: v5.1.4
 - Operating system version: MacOS Monterey 12.5
 - Capture component used: Capture from camera, Capture from texture
 - Capture settings (resolution, frame-rate, codec): default

**To Reproduce**
Steps to reproduce the behavior (CaptureFromCamera ):
1. Create a new Unity 3D URP project
2. Set the color space to "Linear" (Project settings -> Player -> Other Settings)
3. Import the latest AVPro Movie Capture - Ultra Edition.unitypackage
4. Create a new empty scene and add the CaptureFromCamera component
5. Link the component to the main camera and record
6. The recording is much darker than the screen view 

Steps to reproduce the behavior (CaptureFromTexture ):
1. Create a new Unity 3D URP project
2. Set the color space to "Linear" (Project settings -> Player -> Other Settings)
3. Import the latest AVPro Movie Capture - Ultra Edition.unitypackage
4. Create a new empty scene and add the CaptureFromTexture component
5. Duplicate the main camera
6. Create the default render texture and set it as the duplicated camera's output texture
7. Link the component to the render texture and record
8. The recording is much darker than the screen view 

The bug is reproducable in both the editor and the build.

**Screenshots**

Editor view compared to the recorded video:
![image](https://user-images.githubusercontent.com/78732269/232759198-0cf73ebb-fcd8-4821-a417-0dff161b6a84.png)

**Comment by Chris-RH** [comment] 2023-04-26 08:09
Out of interest, what do you get when you take a PNG? Is that the correct colour?

**Comment by vedran-delta** [comment] 2023-04-27 09:15
No, using either of the components the PNG also comes out darker. I'm attaching the captured frames below:

<img src="https://user-images.githubusercontent.com/78732269/234813738-520be91f-b317-4afc-8c90-b0509b880fce.png" height="200">&emsp;<img src="https://user-images.githubusercontent.com/78732269/234813743-f56a67eb-b5fd-4bbd-b7ec-3876ec41f505.png" height="200">

**Comment by Chris-RH** [comment] 2023-04-27 10:00
OK, thanks. 
We are looking into this.

**Comment by Chris-RH** [comment] 2023-05-11 09:38
Our mac dev can't reproduce this I'm afraid

**Comment by vedran-delta** [comment] 2023-05-15 09:52
Are you certain you were using the right color space setting while trying to reproduce the issue?

**Comment by genereddick** [comment] 2023-05-23 02:06
We have the same issue. 

The single texture attached is in Linear color space taken from the camera's render texture but not saved through AV Pro. The first video is Linear color space saved from AV Pro Movie Capture. The second video is also AV Pro but changed to Gamma color space. 

You can see how much darker the linear version is compared to both the gamma version as well as the linear texture not run through Movie Capture.

![Capture_23_05_22_1581766](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/1033793/dd5392a8-c01d-4e73-9484-19d99c4e103e)

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/1033793/8a609fe8-ed50-42f4-874c-78d3f64b0f88

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/1033793/4522a7aa-3c73-4b3b-b1c4-a584280064d7


This is Unity 2022.2.19, URP on iOS 14.

**Comment by genereddick** [comment] 2023-06-15 15:44
Great, thanks!

**Comment by waseem2k** [comment] 2023-06-16 00:37
> I've reproduced this. The issue is caused by Unity picking a floating point texture format for its render target that we don't currently account for. This is also why it was tricky to track down as this format wasn't being chosen on the devices I have access to.
> 
> A fix will make it into the next release.

Hi Morris, 
Thanks for the update. Any idea when this new version be released?

**Comment by Chris-RH** [comment] 2023-06-26 17:02
This has been fixed in the latest release.  Please let us know if it is still an issue after updating.

**Closed** 2023-06-30 09:02 UTC
Labels: Bug 🐛, iOS, macOS, fixed
