### ISSUE TITLE
Screen ResolutionDownScale

### ISSUE THREAD

**Issue by svanderbeck11** [RenderHeads/UnityPlugin-AVProMovieCapture#309] opened 2023-07-28 20:51 UTC
We have an application that was actually taking advantage of what I guess was bug patched in May that was causing Screen Recording to crop rather than scale down to a specific size. Is there a way to still force a crop rather than scale as it broke some features when upgrading? If not it would be great if there was an option to crop to a portion of the screen when recording in screen space.

**Comment by MorrisRH** [comment] 2023-07-29 07:15
Duplicate of #170

**Closed** 2023-08-02 10:17 UTC
Labels: duplicate
