### ISSUE TITLE
CompletedFileWritingAction never called

### ISSUE THREAD

**Issue by jiaming233** [RenderHeads/UnityPlugin-AVProMovieCapture#288] opened 2023-05-25 08:54 UTC
**Describe the bug**
CompletedFileWritingAction never called after screenCapture.StopCapture();
NativePlugin.IsFileWritingComplete(_handle) always return false

**Your Setup (please complete the following information):**
 - Unity version:  Unity2020.3.29f1
 - AVPro Movie Capture version:   version: 5.0.2 (plugin v5.0.0f1-trial)
 - Operating system version: Windows 10  (10.0.19045) 64bit
 - Capture component used:  CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): default value

**To Reproduce**
Set _minimumDiskSpaceMB almost close to disk space, and call StopCapture(true)  automaticlly when there is no enough space

`	
private void CheckFreeDiskSpace()
{
           if (_minimumDiskSpaceMB > 0)
	    {
				if (!IsEnoughDiskSpace())
				{
					Debug.LogWarning("[AVProMovieCapture] Free disk space getting too low.  Stopping capture.");
					StopCapture(true);
				}
			}
}`

**Logs**
[16:18:45]info:[AVProMovieCapture] Stopping capture 0
UnityEngine.Debug:Log (object)
RenderHeads.Media.AVProMovieCapture.CaptureBase:StopCapture (bool,bool,bool) (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:2643)
RenderHeads.Media.AVProMovieCapture.CaptureBase:CheckFreeDiskSpace () (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:3002)
RenderHeads.Media.AVProMovieCapture.CaptureBase:LateUpdate () (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:2927)

[16:20:49]info:[AVProMovieCapture] IsFileWritingComplete  False
UnityEngine.Debug:Log (object)
RenderHeads.Media.AVProMovieCapture.FileWritingHandler:IsFileReady () (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/FileWritingHandler.cs:75)
RenderHeads.Media.AVProMovieCapture.CaptureBase:RemoveCompletedFileWrites () (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:2985)
RenderHeads.Media.AVProMovieCapture.CaptureBase:LateUpdate () (at Assets/SDK/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:2940)

....endlesss "IsFileWritingComplete  False"

**Comment by MorrisRH** [comment] 2023-05-25 11:50
Please try updating to the latest version

**Comment by jiaming233** [comment] 2023-05-26 07:38
> Please try updating to the latest version

OK.

**Comment by OzanUst-M** [comment] 2023-06-06 11:04
Having same issue on iOS.

**Comment by Chris-RH** [comment] 2023-06-09 09:43
@jiaming233,
So we think that this is possibly due to post-processing options being enables (such as fast-start), which require copying the file.  If you're short of disk space then the copy will fail.
So we need to look into how to stop it from locking.  Perhaps fail any post processing if disk space is not sufficient.

@OzanUst-M, 
 _minimumDiskSpaceMB is Windows only; it isn't an option on iOS. So it can't be the same issue.

**Comment by jiaming233** [comment] 2023-06-09 10:47
> 

Thanks for reply!

I will set options.applyFastStart = false and try again next week.

**Comment by jiaming233** [comment] 2023-06-12 02:07
I try to disable post operations by commenting following 3 lines in CaptureBase, which didn't work
`                if (_outputTarget == OutputTarget.VideoFile)
                {
                applyPostOperations = true;
                }
`

Waiting for new release :

**Comment by jiaming233** [comment] 2023-06-12 02:52
I made these 2 modifications and the problem have not been reproduced for now. Just for reference.

![1](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/26813390/07b34bbc-7343-4588-a11e-e6950d39cd62)
![2](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/26813390/0840b26f-7dfb-428a-bf93-33aae9cefa4e)

**Comment by OzanUst-M** [comment] 2023-06-12 08:22
> @jiaming233, So we think that this is possibly due to post-processing options being enables (such as fast-start), which require copying the file. If you're short of disk space then the copy will fail. So we need to look into how to stop it from locking. Perhaps fail any post processing if disk space is not sufficient.
> 
> @OzanUst-M, _minimumDiskSpaceMB is Windows only; it isn't an option on iOS. So it can't be the same issue.

I was talking about CompletedFileWritingAction being never called. It never happens after video recording is done and file is ready to share.

**Comment by Chris-RH** [comment] 2023-06-12 09:42
@OzanUst-M that is a completely different issue then.  Could you open a new issue with all of your details please.

**Comment by RichRH** [comment] 2024-08-02 11:44
Closing this ticket as a workaround to the original issue has been provided (first parameter of 'StopCapture()' should be 'false', not 'true') and it's a duplicate of https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/343.

Cheers,

**Closed by RichRH** 2024-08-02 11:44 UTC
Labels: Bug 🐛, windows
