### ISSUE TITLE
[Bug] Screen capture on Windows producing very dark video

### ISSUE THREAD

**Issue by dganzella** [RenderHeads/UnityPlugin-AVProMovieCapture#381] opened 2024-03-29 18:55 UTC
### Unity Version

2023.2.7f

### AVPro Movie Capture Version

5.2.4

### Which platform(s) are you using?

Windows

### Which OS version(s) are you using?

Windows 11

### Which rendering API(s) are you using?

Direct3D 11, Direct3D 12

### Hardware

Generic-ass MSI windows laptop, with RTX 3060

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

When attempting to record a video, either on editor or on standalone, the video output is much much darker than what we see in the game view itself.

Happens on all codecs, and I tried changing the color space too and nothing helped as well.

Screenshot from the game view:
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/b69f2c52-8219-4633-801f-f00ed6621819)

Video frame result:
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/cc21b095-8f84-4695-bf35-7f381cc49f69)

**Comment by Chris-RH** [comment] 2024-04-03 13:45
This is a duplicate of #55

**Closed by Chris-RH** 2024-04-03 13:45 UTC
Labels: Bug 🐛, duplicate

**Comment by dganzella** [comment] 2024-04-03 14:03
How come its the same thing? hasn't the plugin changed at all in these 4 years?? is there a reason this specific issue is not solved?

**Comment by RichRH** [comment] 2025-01-09 11:27
Hi @dganzella,

Apologies, I understand your frustrations - this has been a bit of a tricky issue for us as results have been inconsistent between (the many) Unity versions due to its wrapping of native textures seemingly changing.

I've also posted to #55 with more information but just wanted to check in personally to see if this is still an issue with latest Unity/plugin?

Cheers,
