### ISSUE TITLE
iPhone, the Bluetooth connection will be disconnected and the sound will come from the mobile device.

### ISSUE THREAD

**Issue by choigawoon** [RenderHeads/UnityPlugin-AVProMovieCapture#314] opened 2023-08-07 03:49 UTC
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**

I tried using the recording function with the Bluetooth earphone connected to the iPhone.
when start recording, the Bluetooth connection will be disconnected and the sound will come from the mobile device.

I've had this problem before and applied it.
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/210

i want to capture audios from game and mic both.

here`s my code snippet
```
#if UNITY_IOS
if (_capture.AudioCaptureSource == AudioCaptureSource.Microphone)
{
    if (ur.RecordMode == ScreenRecordMode.ScreenAndGameAudioAndMic)
    {
        NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers |
                                  NativePlugin.MicrophoneRecordingOptions.DefaultToSpeaker;
        NativePlugin.SetMicrophoneRecordingHint(true, options);
    }
    else
    {
        NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers;
        NativePlugin.SetMicrophoneRecordingHint(true, options);
    }
}
#endif
```

could you give me an advice for me? how to fix it?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5f1
 - AVPro Movie Capture version: 5.1.0f1-ultra (scripts v5.1.2)
 - Operating system version: ios
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by choigawoon** [comment] 2023-08-07 04:31
forget to mention it, i want to capture audios from game and mic both.

**Comment by MorrisRH** [comment] 2023-08-07 06:55
Duplicate of #301

**Comment by MorrisRH** [comment] 2023-09-04 09:29
Turned out to not be a duplicate of #301 but is related.
I've fixed NativePlugin.SetMicrophoneRecordingHint so it should no longer disable bluetooth headphones when being called.

**Comment by Chris-RH** [comment] 2023-09-12 14:34
AVPro Movie Capture version 5.1.8 has been released. Please let us know if it has not fixed your issue.

**Comment by choigawoon** [comment] 2023-09-20 05:13
when a user try to record with a bluetooth headset and a microphone, there is no way to handle it.
during recording, sound is come from the device speaker, after recording, sound is come from bluetooth.


https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/199
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/210

here`s my code snippet. 
```
                            if (_capture.AudioCaptureSource == AudioCaptureSource.Microphone)
                            {
                                if (ur.RecordMode == ScreenRecordMode.ScreenAndGameAudioAndMic)
                                {
                                    NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers |
                                                                                      NativePlugin.MicrophoneRecordingOptions.DefaultToSpeaker |
                                                                                      NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
                                    NativePlugin.SetMicrophoneRecordingHint(true, options);
                                }
                                else
                                {
                                    NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers |
                                                                                      NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
                                    NativePlugin.SetMicrophoneRecordingHint(true, options);
                                }
                            }
```

**Comment by choigawoon** [comment] 2023-10-25 02:12
> The configuration around microphone capture is unfortunately quite complicated just due to how things work on iOS. With the following:
> 
> ```cs
> NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.None;
> NativePlugin.SetMicrophoneRecordingHint(true, options);
> ```
> 
> audio will play via the bluetooth earphones with the device microphone being used for capture.
> 
> With the following:
> 
> ```cs
> NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
> NativePlugin.SetMicrophoneRecordingHint(true, options);
> ```
> 
> this puts the bluetooth earphones into handsfree mode and enables the microphone. You need to make sure the audio input device index is set to 1 (0 is the device microphone). This is `Force Audio Input Device Index` in the iOS audio inspector properties. Audio will continue playing through the headphones this way and audio will be captured from the bluetooth microphone. Because the earphones are now in handsfree mode, there will be a drop in the audio quality being played. ![Screenshot 2023-10-24 at 12 01 26](https://user-images.githubusercontent.com/46530460/277637874-ac27fe8a-a97e-4b10-9258-d601027ae266.png)

It sounds really complicated.

1.
I'm trying to determine whether the user is currently using the speaker or Bluetooth and set it accordingly, but I can't find a related function.

If it's the speaker, I intend to handle it as usual,
but if it's Bluetooth, I plan to go by the method you mentioned.

2
In the game I developed, both music and microphone need to be recorded at the same time, but that part seems not to work properly. Instead of the game music being cleanly recorded, it seems like the sound flowing out of the speaker is being recorded again by the microphone. Is that correct?

Please note that nuances might differ slightly between languages, so if there's any specific intent or meaning you wanted to capture, do let me know!

**Comment by MorrisRH** [comment] 2023-10-25 15:27
We don't support capturing two audio streams and mixing them which is what you're after. It's just a quirk of the device that the microphone can pick up the currently playing audio from the speaker.

I would try using Unity's Microphone component and putting its audio into your scene so that the audio listener can then pick it up which in turn would be captured by the plugin.

**Closed** 2023-11-17 10:42 UTC
Labels: Bug 🐛, iOS, fixed
