### ISSUE TITLE
Unable to capture Transparent Renders with Apple ProRes 4444

### ISSUE THREAD

**Issue by pnostudiodeveloper** [RenderHeads/UnityPlugin-AVProMovieCapture#165] opened 2022-05-04 19:27 UTC
**Describe the bug**

My ProRes 4444 Renders come out with an opaque background even though I've selected "Support Transparency" and followed the manual to select "Solid Color" with a color with alpha of 0 on the Camera.

When I select HEVC, the renders render transparent - so I think my general set up is correct.

- URP Pipeline
- Orthographic Camera

When I select "Solid Color", the ProRes 4444 render renders the Camera Background Color with an Alpha of 1 even though it's set to 0. (Opaque red background, if I had selected red as the background color with alpha of 0).

When I select "Uninitialized" for the Camera Background, the ProRes 4444 render comes out with an opaque black background, even though in the render preview it's the typical chaotic visual trails that one usually sees after selecting the Uninitialized setting in the Editor.

**Your Setup (please complete the following information):**
 - Unity version:  2021.2.19f1
 - AVPro Movie Capture version: 4.7.6
 - Operating system version: MacOS 12.2.1
 - Capture component used: Capture from Camera
 - Capture settings (resolution, frame-rate, codec):   ProRes 4:4:4:4,  Framerate - 30,   1920 x 1080,   Average Bitrate 30,   Quality 1, Keyframe 0,   Support Transparency - Yes,   Enable Fragmented - No,   
 

**To Reproduce**
1. Capture scene using above settings on MacOS
2. Import to Final Cut X - place anything underneath the video to check transparency
3. ProRes 4444 render is opaque above other video layers - HEVC render is transparent above other video layers

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by AndrewRH** [comment] 2022-05-04 20:35
This could be related to URP.  Please could you try:
1) disabling all post-process effects to see whether that helps
2) try the same steps but in a project without URP to see if that helps

This way we can narrow down the cause.

Thanks,

**Comment by pnostudiodeveloper** [comment] 2022-05-04 21:01
1.  Post processing was already disabled.
2.  The same issue is present when I created a completely empty Built-In Pipeline project.  
 HEVC renders transparent, ProRes 4444 does not.

https://user-images.githubusercontent.com/22384156/166825178-7fc8e3a0-fb3f-46cf-b35b-cc304031f32a.mov


Render files are attached

https://user-images.githubusercontent.com/22384156/166825167-289a1d7b-0a9f-4123-9dd3-48bc901fe8a8.mov

**Comment by MorrisRH** [comment] 2022-05-05 09:11
I'm unable to reproduce this.

Setup is as follows:
- Unity 2021.3.1f1
- AVPro Movie Capture 4.7.10-trial
- macOS 12.3.1
- Capture from Camera

Output video:
https://user-images.githubusercontent.com/46530460/166893953-da4a33b4-36a9-47ae-8343-5f4946fe4ef0.mov

Frame grabbed using ffmpeg:
![frame0000](https://user-images.githubusercontent.com/46530460/166894076-bfcc6b28-40ed-44db-b3df-cfe7e9aab144.png)

**Comment by pnostudiodeveloper** [comment] 2022-05-05 14:16
Would it be possible for you to send me the Unity project you made so that I can examine your Unity project set up for any differences and also test it on my device?  My email is visualmusicdesign@gmail.com .  Would appreciate.

Also, I didn’t previously mention I am testing in the Silicon editor on a MacBook Pro M1 Pro.  Maybe silicon could have something to do with it?

**Comment by pnostudiodeveloper** [comment] 2022-05-05 19:51
Hello, I tested my repro project on a 2018 Intel MacBook Pro, and it rendered ProRes 4:4:4:4 transparent without changing any settings.

It appears the issue is related to Silicon architecture.

Can you test in the Editor on Mac Silicon please?

Thank you

**Comment by MorrisRH** [comment] 2022-05-06 09:19
My testing was performed on an Apple Silicon Mac mini.

**Comment by pnostudiodeveloper** [comment] 2022-05-06 13:45
1.   May I ask if you were also using the Silicon version of Unity Editor?
2. Are you also using Orthographic camera and recording the Game view?

I’m sorry, but this is easily reproducible for me.  The functionality is broken for my use case, and it’s quite frustrating.

Could you send me the repro project you created so that I see the setup and see if it helps me understand how to make this work?  
My email is visualmusicdesign@gmail.com


Thank you

**Comment by MorrisRH** [comment] 2022-05-06 16:35
1. Yes, the Apple Silicon version of the editor was used
2. Tried all sorts of camera configurations, the only thing that had any affect was enabling/disabling Post Processing in the Rendering section of the Camera inspector, with Post Processing enabled no alpha channel was written.

I just modified the URP example scene:
[URPTest.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/8642118/URPTest.zip)

Output movie:
![MovieCapture_2022-05-06_17-17-29_692x408](https://user-images.githubusercontent.com/46530460/167172604-a87a567d-0bf8-45fc-af5d-9286ccf7787e.mov)

Frame grab:
![MovieCapture_2022-05-06_17-17-29_692x408](https://user-images.githubusercontent.com/46530460/167172552-382f40e9-9d2f-4f29-b818-f003a84591e2.png)

**Comment by pnostudiodeveloper** [comment] 2022-05-06 17:16
When I run the project you sent and capture the Game view without changing anything, it renders with an opaque green background.  Attaching the render.

[https://www.dropbox.com/s/9w08f6nnh32xifv/MovieCapture_2022-05-06_10-12-19_1536x768.mov?dl=1](url)

Frame grab:
![Screen Shot 2022-05-06 at 10 15 42 AM](https://user-images.githubusercontent.com/22384156/167180821-d6100983-035f-4586-939b-7dd5f61ab9b8.png)


- I am testing on a MacBook Pro M1 Pro in Unity 2021.2.19f1 Silicon.  Maybe this could somehow be hardware or Unity version specific?

- I will try installing Unity 2021.2.3 right now, which I can see was the version you were testing your project in.

**Comment by pnostudiodeveloper** [comment] 2022-05-06 17:56
I tested your repro project with no changes on Unity 2021.3.2f1 Intel version - but still on the same 2021 MacBook Pro M1 Pro - and it had the same render result - opaque green background.

So likely not a Silicon / Intel issue or Unity version issue - possibly could be hardware specific to the new MacBook Pro?  Very strange.

**Comment by MorrisRH** [comment] 2022-05-06 18:19
Interesting. The M1 Pro and Max have hardware encoding for ProRes so I expect this issue is specific to the hardware.
I'll investigate further and see where this clue leads.

**Comment by pnostudiodeveloper** [comment] 2022-05-06 18:22
Thank you, much appreciated

**Comment by MorrisRH** [comment] 2022-05-07 12:50
I've done some reading around on this issue and it does appear to limited to the M1 Pro and M1 Max chips. My understanding is that Apple are aware but whether or not a solution is coming from them I do not know. 

It seems some people have had some success using alternative pixel formats for the input to the encoder. I've hacked together a version of the plugin that uses one of the suggested pixel formats. @pnostudiodeveloper if you're willing could you test it? You just need to replace the bundle located at ``Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/macOS`` with the one in the attached zip file (it does require latest scripts but will work fine in the test project I sent previously). Make sure to close the editor before replacing the plugin to make sure it updates.

Unfortunately I don't have access to a device with an M1 Pro or Max chip so there may be a bit of back and forth to get this issue resolved if you're okay with that.

[AVProMovieCapture.bundle.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/8645153/AVProMovieCapture.bundle.zip)

**Comment by pnostudiodeveloper** [comment] 2022-05-07 13:02
I think that actually worked!

It is still opaque green when opened in Quicktime Player, but it is transparent when overlaid on other videos in Final Cut X.

I'm leaving for the weekend in minutes and won't have access to my computer until Monday so I can't fully test the implementation, but for the moment it seems like this is giving the same result as transparent renders on the Intel Mac.

Here is the render:
https://www.dropbox.com/s/m1wqi98g1iuoyws/MovieCapture_2022-05-07_05-58-49_2072x1128.mov?dl=1

Thank you for looking into it

**Comment by MorrisRH** [comment] 2022-05-08 09:45
That render looks exactly as I would expect. I'll turn the hack into a proper fix.

**Comment by MorrisRH** [comment] 2022-05-11 14:47
I've now properly implemented the work around and it will be available in the next release, version 4.7.11.

**Comment by AndrewRH** [comment] 2022-05-12 09:27
AVPro Movie Capture 4.7.11 has been released and includes a fix for this issue.  Please let us know whether this resolves it for you.

**Comment by pnostudiodeveloper** [comment] 2022-05-12 23:22
The original issue has been resolved. 

Thank you!


Unfortunately, I'm now having trouble over on the Windows side, where I'm also trying to get Transparent video capture working.  

- I am trying to use either Lagarith of MagicYUV to capture Transparent video on Windows.

- I have installed and configured both of those compression encoders on my computer.

- AVPro MovieCapture finds both Lagarith and MagicYUV and lists them in the list of available encoders.  

- However, when I set it to use either of them, I get the error at runtime:
`Failed to create recorder`


1.  Can you verify if either Lagarith and MagicYUV should still work with MovieCapture?  Have they been tested recently?  I don't want to bang my head against this wall if they aren't verified to be working with MovieCapture recently.


2.  Should I make a new issue for this?  Let me know.


3.  I was trying to use the free version of MagicYUV from their website, which I know is a bit older.  Let me know if you have only tested with the commercial version.

**Comment by MorrisRH** [comment] 2022-05-13 09:22
I've started a new issue (#169) for your windows troubles as it may get lost otherwise.
Closing this one now as fixed for macOS.

**Closed by MorrisRH** 2022-05-13 09:22 UTC
Labels: macOS, fixed
