### ISSUE TITLE
Android - Recorded video stutters

### ISSUE THREAD

**Issue by vladtaranenkoSA** [RenderHeads/UnityPlugin-AVProMovieCapture#207] opened 2022-10-18 15:02 UTC
Recorded video stutters or distorted
Recorded video on device Poco X3 Pro stutters. While inspecting video in player noticed duplicated frames after each 3-6 frames.
Its also seems like on different android devices same app produces videos with different encoding parameters, like codec profile (reported video got baseline, on Motorola Edge 20 got main, no stuttering but video was distorted in some points). If you could clear up where these differences come from, if its possible to tweak codec initialization parameters in some way other than VideoHints, would be also great. Thanks.

**Setup**
 - Unity version: 2019.4.23f1
 - AVPro Movie Capture version: 5.0.4
 - Operating system version: Android 11 RKQ1.200826.002 MIUI Global 12.5.7 Stable
 - Capture component used: CaptureFromCamera, Offline rendering, "Allow vsync disable" enabled, "Wait for end of frame" enabled. Also tried component TimelineController - no effect
 - Capture settings (resolution, frame-rate, codec): 720x1280, 30 fps., h264

**Steps to reproduce the behavior:**
1. Record the video
2. Play and inspect video in any player
3. Video stutters

**Screenshots**
CaptureFromCamera setup
![image](https://user-images.githubusercontent.com/92296634/196467279-e3cdc5c1-fa41-4b59-bc52-87d0fbd8dc62.png)
![image](https://user-images.githubusercontent.com/92296634/196467525-46c159fd-24c5-41de-a0ee-c5469f838a6e.png)

**Videos**
From Poco X3 Pro
https://user-images.githubusercontent.com/92296634/196464549-bde11ed8-e017-41eb-a897-7e58a4191232.mp4

From Motorola Edge 20 Lite
https://user-images.githubusercontent.com/92296634/197145679-5fd3a9e0-cb3d-4ba8-bb49-571a660f7e9d.mp4

**Comment by MorrisRH** [comment] 2022-10-19 14:57
> Its also seems like on different android devices same app produces videos with different encoding parameters, like codec profile (reported video got baseline, on Motorola Edge 20 got main, no stuttering but video was distorted in some points). If you could clear up where these differences come from, if its possible to tweak codec initialization parameters in some way other than VideoHints, would be also great. Thanks.

The profile level is not something we can control, the underlying platform drivers will determine what's best.
No idea what you mean by "distorted in some points". If you could provide an example we'll investigate.

**Comment by aengmo1** [comment] 2022-10-21 07:51
Hi Morris,

Do you know if there is an alternative way of controlling the codec? Or are we forced to basically rule out devices that just decide to encode the video with a profile that stutters? Could it be some settings on the device?

**Comment by vladtaranenkoSA** [comment] 2022-10-21 08:07
Added motorola video at the bottom of original post

**Comment by MorrisRH** [comment] 2022-10-22 09:33
Hey @aengmo1
Profile levels are based on the resolution and bitrate being encoded and have nothing to do with the stuttering being seen.

**Comment by MorrisRH** [comment] 2022-10-22 09:35
Hey @vladtaranenkoSA,
Did you try capturing with "Allow V Sync Disable" unchecked?

**Comment by MorrisRH** [comment] 2022-10-24 08:01
I've reproduced the first issue (with the poco) here. It can be worked around by unchecking "Allow V Sync Disable". This will lead to slower captures on some hardware (esp. hardware that can support > 60fps).
The second issue (the Motorola) is a bit more complex, I don't have a reproducible case (yet) but I'm pretty sure I know what is going awry. Again, unchecking "Allow V Sync Disable" will probably help.

**Comment by vladtaranenkoSA** [comment] 2022-10-24 08:23
@MorrisRH 
Hello
Just tried it with unchecking "Allow V Sync Disable" - still stutters.
And regarding bitrate, with default 0 I get video with 1280x720 resolution and 5mpbs bitrate. Not sure if its enough to fall in higher encoding profile.

**Comment by vladtaranenkoSA** [comment] 2022-10-24 08:25
I could also see that there is some problems with audio stream in broken poco video. Could it be the case?

**Comment by Cham-TF** [comment] 2022-10-24 13:14
@MorrisRH (I work with Vlad) could you send us the project that you are using to make the poco work?  It would be a good base line for us to see it working on our device with your project and then perhaps we can focus on what is different with our setup and settings.

**Comment by MorrisRH** [comment] 2022-10-24 13:22
> I could also see that there is some problems with audio stream in broken poco video. Could it be the case?

The video you sent didn't seem to contain audio from a capture so I've no idea if there is an issue there or not.

**Comment by MorrisRH** [comment] 2022-10-24 13:23
> @MorrisRH (I work with Vlad) could you send us the Unity project that you are using to make the poco work? It would be a good base line for us to see it working on our device with your project and then perhaps we can focus on what is different with our setup and settings in our Unity project

I just used the camera capture demo scene, configured for offline rendering with the settings that were pasted above.

**Comment by Cham-TF** [comment] 2022-10-25 18:09
@MorrisRH what Unity renderer are you using in your project? Default or URP?  what version of gradle are you using?

**Comment by Cham-TF** [comment] 2022-10-25 21:55
@MorrisRH let me know about the questions above, but I built the example scene you mentioned in a separate project and ran it on our Poco X3 Pro and was not able to reproduce the stutter with "Allow V Sync Disable" set to true or false.  Given that and the fact that our main app did not get better by unchecking "Allow V Sync Disable" has me wondering if it is a different problem.  Happy to send you my example project if you wish to check it out.

**Comment by Cham-TF** [comment] 2022-10-27 15:00
@MorrisRH I also made the example use our URP assets for rendering and still could not reproduce the skipping.  Can you share with me your project to try?

**Comment by MorrisRH** [comment] 2022-10-28 08:05
Hey @Cham-TF 

I was just using the built-in unity renderer, I haven't tested with URP but cannot think of a reason for that to make a difference. I don't have a separate project to send, it was just using the demo scene we provide with the plugin.

I was testing on a Pixel 4 and it occasionally showed the stuttering, it was no where near as bad as the video you posted though. For some reason the plugin isn't getting the next frame through from Unity so it captures the same frame twice. I expect scene complexity might be an influence so very simple scenes would not show the issue.

Unchecking "Allow V Sync Disable" stops offline captures from running as fast as possible so they behave the same as realtime captures although without frame dropping. On the pixel 4 it allows us to capture at up to 120fps, so about 4x faster than normal. Different hardware will have different max frame rates though so there may only be a small speed up.

**Comment by Cham-TF** [comment] 2022-10-28 13:49
Thanks Morris.  We will certainly Uncheck "Allow V Sync Disable".  Though, since it did not seem to solve the problem in our app (at least on the Poco X3 Pro) , my plan of attack now is to expose the recording parameters  in our real app and experiment with the settings on the devices that have the stutter. if there is code instrumentation that you think would help give a sense of what is happening or areas of code you think I should examine for determining what is happening. Please let me know and I can check that.

**Comment by Cham-TF** [comment] 2022-11-04 08:36
@MorrisRH any specific area of your code that I can instrument with information that might help diagnose this problem "For some reason the plugin isn't getting the next frame through from Unity so it captures the same frame twice."?

**Comment by Cham-TF** [comment] 2022-11-04 08:43
perhaps a bug with WaitForEndOfFrame?

**Comment by Cham-TF** [comment] 2022-11-04 15:45
@MorrisRH Looking at the code it does seem like WaitForEndOfFrame could be acting different than expected for our case.  We saw some code marked as EXPERIMENTAL_FRAME_PAUSE, that seemed to also indicate someone at Renderheads was experimenting with something similar.  Enabling this code drastically improved the stuttering.  There is still a bit of hitching in the first 2-3 sec but then it runs very well after that.  Any thoughts on this?

**Comment by Cham-TF** [comment] 2022-11-08 16:10
@MorrisRH I made a sample project based on your demo that reproduces the problem with free unity assets etc.  Not sure I should post it here since it has all your code in it, so perhaps we can email you a link?  or let me know how to best get it to you.

**Comment by MorrisRH** [comment] 2022-11-08 19:06
Hey @Cham-TF 
Please email it (or a link to it if it's big) to unitysupport@renderheads.com and mention this issue in the subject. I'll be sure to take a look.

We're currently preparing to release version 5.1 (end of the week if all goes to plan) which will have some changes in it that will hopefully help with this issue.

**Comment by Cham-TF** [comment] 2022-11-09 02:59
@MorrisRH ok an email was sent.  Thanks

**Comment by Chris-RH** [comment] 2022-12-01 07:29
Version 5.1.0 has been release. Please let us know if it has not fixed this issue.

**Closed** 2022-12-07 18:11 UTC
Labels: Bug 🐛, fixed, Android
