### ISSUE TITLE
[Bug] Microphone doesn't provide Audio when the next click on "Start Video Recording" button happens too fast after stopping recording.

### ISSUE THREAD

**Issue by makakaorg** [RenderHeads/UnityPlugin-AVProMovieCapture#388] opened 2024-05-16 19:31 UTC
### Unity Version

2022.3.29

### AVPro Movie Capture Version

5.2.4-Mobile Edition build 1387

### Which platform(s) are you using?

iOS

### Which OS version(s) are you using?

iOS 17.5

### Which rendering API(s) are you using?

Metal

### Hardware

iPhone XS Max

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Microphone

### Audio codecs

AAC

### The issue

The microphone doesn't provide Audio when the next click on "Start Video Recording" button happens too fast after stopping recording.

It's related to short and long videos.
It can happen even if I block "Start Video Recording" until the  captureBase.CompletedFileWritingAction dispatched.

**Comment by makakaorg** [comment] 2024-05-16 20:11
So, in the resulting video, there is no sound.

**Comment by MorrisRH** [comment] 2024-08-29 12:23
Unable to reproduce this in a fresh project using the following:
- Unity 2022.3.44f1
- AVPro Movie Capture 5.3.0 Mobile
- Capture from Screen component set-up to capture audio from Microphone
- iPhone 12 running iOS 17.5.1

Simple scene with a button that stops the current capture and starts a new one immediately.

**Comment by Chris-RH** [comment] 2024-09-03 09:02
Could you provide any more info on how to reproduce this @makakaorg?

**Comment by Chris-RH** [comment] 2024-09-06 09:37
Could you provide any more info on how to reproduce this @makakaorg?

**Comment by Chris-RH** [comment] 2024-09-20 10:19
closing due to lack of reply

**Closed by Chris-RH** 2024-09-20 10:19 UTC
Labels: Bug 🐛, iOS, CNR 🤷
