### ISSUE TITLE
Transparency Issue

### ISSUE THREAD

**Issue by nantreee** [RenderHeads/UnityPlugin-AVProMovieCapture#50] opened 2020-05-08 18:09 UTC
**Describe the bug**
The images turn to a pink/purple-ish shade when the "support transparency" toggle turned on.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.12f1
 - AVPro Movie Capture version: 4.2.2 (scripts v4.3.1)
 - Operating system version: macOS Mojave
 - Capture component used: in editor capture
 - Capture settings (resolution, frame-rate, codec): 1920x1080, 60fps, PNG image sequence

**Screenshots**
![frame-000011](https://user-images.githubusercontent.com/2031010/81435105-1f644c00-911c-11ea-8ccd-08dfb0c36e1c.png)
![frame-000011](https://user-images.githubusercontent.com/2031010/81435119-23906980-911c-11ea-8435-bb4c9fe86fc3.png)

**Comment by MorrisRH** [comment] 2020-05-09 11:20
So far I've been unable to reproduce this. I am running macOS Catalina though so it's quite possible this is an issue Mojave. I'll report back when I get access to a machine with Mojave installed.

**Comment by MorrisRH** [comment] 2020-05-10 21:47
Reproduced. Will be fixed in the next release.

**Comment by AndrewRH** [comment] 2020-05-11 13:22
The new version 4.3.3 with this fixed has been released.  I'm closing this issue.
Thanks,

**Closed by AndrewRH** 2020-05-11 13:22 UTC
Labels: bug, macOS
