### ISSUE TITLE
Unity Bug - Terrain Grass animates too fast during offline rendering

### ISSUE THREAD

**Issue by Torantulino** [RenderHeads/UnityPlugin-AVProMovieCapture#115] opened 2021-08-16 15:25 UTC
**Describe the bug**
Recording in offline mode causes animations such as swaying grass on Unity's Terrain system to speed up dramatically.
I am looking to switch from another unity plug-in with is able to record offline capture without this effect. This is currently the only thing preventing me from making the switch.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.23
 - AVPro Movie Capture version:  AVProMovieCapture-v4.6.5-Trial
 - Operating system version: Windows 10
 - Capture component used: Capture from camera 360 VR (though I think the same is true for others)
 - Capture settings (resolution, frame-rate, codec): 2048x2048, 60fps

**To Reproduce**
1. Set up an intensive scene that requires offline rendering to record smoothly.
2. Ensure your scene has a unity terrain with swaying grass details
3. Press play and run an offline capture.
4. Watch back the recorded video and compare grass sway speed to that observed in the editor.

**Comment by AndrewRH** [comment] 2021-08-16 16:32
Thanks we will investigate this - we haven't tried to capture unity terrain grass before and are surprised to hear that it works differently.  It should hopefully be an easy fix.  We will get back to you shortly.

Thanks,

**Comment by AndrewRH** [comment] 2021-08-16 16:33
Are you just using Unity's built-in terrain foliage system for the grass?

**Comment by AndrewRH** [comment] 2021-08-16 18:14
We have reproduced the issue.  As far as we can tell calling camera.Render() causes Unity's terrain/grass animation system to update time.. This seems like a bug to us.  We will dig further to see if it is fixed in a later Unity version, or whether a workaround can be made.

Thanks,

**Comment by AndrewRH** [comment] 2021-08-17 07:49
Hi,

We have reporting this as a bug to Unity.  The only workaround we have found is to manually adjust the Terrain wind speed.

So if you're capturing 360 (cubemap) it will be rendering the scene 6 times, so you need to divide the wind speed by 6.

![image](https://user-images.githubusercontent.com/5418126/129685775-0891a613-53be-4acd-a4b7-248e8c1e42a4.png)

We will considering making this automatic as part of the capture in the future, but for now this is clearly a bug in Unity and we will wait for their response to the bug report.

I don't think any other capture solution for 360 captures will work any better.

Does that help?

Thanks,

**Comment by AndrewRH** [comment] 2021-08-17 07:57
For reference here is the bug reported sent to Unity: https://fogbugz.unity3d.com/default.asp?1358679_6d38fjd24bcqaj69

**Comment by Torantulino** [comment] 2021-08-17 12:02
Hey,

Oh wow I see, so it's simply due to the number of cameras rendering?
Thanks, I'll try that now and let you know if it doesn't work, or whether I
run into this problem elsewhere.

I am very impressed with the fast response!

Kind regards,



Toran Bruce Richards
Significant Gravitas

**Comment by AndrewRH** [comment] 2021-08-17 12:27
Hi,

Yes it's actually not caused by normal camera rendering in your scene, but calls in the script to camera.Render() or camera.RenderToCubemap() which is what we do internally in our plugin.  It seems each time you call one of these, Unity is adjusting the terrain animation timer.  RenderToCubemap() effectively does 6 render calls (one for each face of the cube), so this one increases the timer 6 times.

Thanks for bringing this to our attention,

**Comment by AndrewRH** [comment] 2021-09-01 10:18
Closing this as Unity are working on it and not our issue

**Closed by AndrewRH** 2021-09-01 10:18 UTC
Labels: wontfix, not a bug
