### ISSUE TITLE
Audio is still captured when capture is paused

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#311] opened 2023-08-01 11:11 UTC
We've noticed that audio recording isn't paused along with video recording when using videoCapture.PauseCapture() and videoCapture.ResumeCapture(). Repro by starting a recording, pausing it while making noise, resuming it and stopping it. The audio recorded when the capture was paused is played on top of the video, meaning they're massively out of sync.

 - Unity version: 2021.3
 - AVPro Movie Capture version: 5.1.7
 - Operating system version: Unity Editor on OSX
 - Capture component used: Webcam
 - Capture settings: Capturing audio via microphone

**Comment by Chris-RH** [comment] 2023-08-08 08:03
Hi @tomkail 

I'm afraid our macOS dev is on annual leave at the moment, but he will be back in the office from 21st.

**Comment by tomkail** [comment] 2023-08-08 08:04
Thanks for letting me know! Do you believe it’s platform specific?

**Comment by Chris-RH** [comment] 2023-08-09 14:13
It appears to work as expected on Windows.

**Comment by MorrisRH** [comment] 2023-08-31 13:20
This issue has been fixed and will make it into the next release (5.1.8)

**Comment by tomkail** [comment] 2023-09-05 08:31
Thanks! Any word on when this will be? It's currently a release blocker for us.

**Comment by tomkail** [comment] 2023-09-05 08:34
Also; can you confirm this will also fix the same bug on iOS? I'd omitted it from the description above but it seems to occur there too.

**Comment by Chris-RH** [comment] 2023-09-12 13:40
AVPro Movie Capture version 5.1.8 has been released.  Please let us know if it has not fixed your issue.

**Comment by tomkail** [comment] 2023-09-18 09:05
Hello! Any word on this? Sorry to keep flagging it up but this has been preventing us from shipping for nearly 2 months now and we're getting quite antsy.

**Comment by Chris-RH** [comment] 2023-09-27 12:26
Hey @tomkail 

Any additional info as above would be appreciated please.

**Comment by Chris-RH** [comment] 2023-10-03 09:45
closing due to lack of reply

**Comment by tomkail** [comment] 2023-10-03 09:47
Ah sorry - we couldn't wait any longer so we shipped without it. We've not had time to look into it since but I'll try to find time to soon.

**Comment by tomkail** [comment] 2023-11-09 09:56
Hi! If it's possible to re-open this, we're looking to get this feature into the next version of our app and we're still encountering the slow-motion issue on iOS.
I've attached a c# script of our setup; but I don't believe there's anything special about it.

Hope that helps!

[LiveVideoRecordingUIView.cs.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/13306602/LiveVideoRecordingUIView.cs.zip)

**Comment by MorrisRH** [comment] 2023-11-13 10:00
Hey @tomkail, I still cannot reproduce this. My hunch is that Unity's sample rate is being changed by something external but I've no idea what. If you could outline the steps you take to reproduce this that would be great. It would also be handy to know if this is happening with specific hardware or OS versions.

**Comment by yjosx** [comment] 2023-11-14 07:54
i'm facing the same issue.
in my case, i'm using capture from texture and the audio is set to microphone,
When I run it on the iPad, it works perfectly fine, but on the iPhone, there is a slow down in the audio after resume.
the device is ipad pro 2020 and iphone 14 pro ,both ios version is 16.6

**Comment by tomkail** [comment] 2023-11-16 14:40
Sorry, we’re crunching right now and I won’t be able to get you any more
demos for a bit. We’re going to ship without this feature again. Maybe it’s
a device issue, as the other poster suggests?

**Comment by MorrisRH** [comment] 2023-11-17 10:29
Are you able to reproduce the behaviour using one of our demo scenes?

I take it the pause/resume behaviour is entirely within the application and not as a result of moving the app to the background (switching to another app, receiving a call, etc.)?

Is anything else happening in the scene whilst the capture is paused related to the microphone or audio playback?

**Comment by tomkail** [comment] 2023-11-17 10:46
I’ve not tried the demos in ages, sorry! Nothing special is happening in
the scene, we’re just pausing and resuming.

**Comment by MorrisRH** [comment] 2023-12-04 10:45
Hey @tomkail, can you share one of these captures? I'd like to get a better feel for what you describe is happening. Still not able to reproduce this.

**Comment by yjosx** [comment] 2023-12-10 10:15
Hey @tomkail , Are you manually calling the microphone.start() method while the video is recording or pausing? I have done this, is this likely to cause the changes described above?

**Comment by tomkail** [comment] 2023-12-11 16:43
Might be a while till we can spend more time on this; sorry! We're not calling Microphone.Start; our impression was that AVPro handled that part automatically?

**Comment by Chris-RH** [comment] 2024-03-19 12:42
Hi @tomkail, 

Is there any chance that you could share a capture please?

**Closed** 2024-03-26 14:28 UTC
Labels: Bug 🐛, iOS, macOS, CNR 🤷
