### ISSUE TITLE
Android coloration issue

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProMovieCapture#190] opened 2022-08-09 00:15 UTC
**Describe the bug**
Funny colors on a Pixel 5a

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.7f11
 - AVPro Movie Capture version: 5.0.1
 - Operating system version: Android 12
 - Capture component used: FromTexture
 - Capture settings (resolution, frame-rate, codec): 1080p, 30fps, h264 (YUV420)

**To Reproduce**
1. Record anything with the Pixel 5a
2. Notice the coloration issues

It looks to me like a metadata issue, like the colors are being written in one colorspace and interpreted as another?

**Logs**
I don't have access to a Physical 5a yet, so I can't post the full logcat. What is sent via Unity Logs look entirely normal:
```
[AVProMovieCapture] Start File Capture: 1080x1920 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'Default Microphone' acodec:'AAC' to file: '/storage/emulated/0/Android/data/com.dashcambike.dashcamapp/files/Captures/BikeCam_00_2022-08-07_16-22-43_1080x1920.mp4'
[AVProMovieCapture] Stopping capture 17200
[AVProMovieCapture] File processing complete
```
If you don't have a Pixel 5a, let me know and I will try to borrow one to get you a full logcat here.

**Screenshots**
<img width="138" alt="image" src="https://user-images.githubusercontent.com/537316/183535584-3a15bafb-30ea-4166-9712-a32c1b9ac559.png">

**Videos**
I have attached the full video without any trimming so you can inspect the metadata. Note there is a loud beep at the beginning of the video so please take note of your headphone/speaker volume before you hit play.
https://user-images.githubusercontent.com/537316/183535822-6561c207-4597-4c11-b9f3-1a85db4e8787.mp4

**Comment by Chris-RH** [comment] 2022-08-09 06:43
(Note, also  Xiaomi Mi 11 and 12)

**Comment by Chris-RH** [comment] 2022-08-09 06:52
Thanks @artoonie, a full logcat would be great if you could get one please :)

**Comment by MorrisRH** [comment] 2022-08-09 08:45
Android 12 has thrown a slight spanner in the works, we're working on a fix at the moment. If you could send on the logcat output that would be really useful.

**Comment by artoonie** [comment] 2022-08-09 22:00
Thanks all - will try do. None of my devices have Android 12, so I'm working on training the user who submitted the above video to get us a `logcat`.

**Comment by MorrisRH** [comment] 2022-08-10 10:09
This should be fixed with the next release (5.0.2)

**Comment by ModischFabrications** [comment] 2022-08-19 07:54
Same error on Pixel 6 (with AR Core), see attached image. Log contains a few interesting events, attaching here in case it's part of the problem: 

```
2022/08/19 09:39:09.363 30527 30665 Error StartedCameraController(0) Saw capture failed event, failure: android.hardware.camera2.CaptureFailure@34988d9.
2022/08/19 09:39:09.595 30527 31054 Info AVProMovieCapture ⚠️ VideoRecorderAPI28::copyPlaneToInputBuffer - input buffer size is smaller than the source, the plane will not be copied
2022/08/19 09:39:26.716 30527 31065 Debug CCodecBufferChannel [c2.exynos.h264.encoder#353] MediaCodec discarded an unknown buffer
```

![image](https://user-images.githubusercontent.com/25404728/185570671-e861d74c-2bf7-4b6d-92cc-63bdc8a3ce40.png)

Do you have an estimation on the new release?

**Comment by Chris-RH** [comment] 2022-08-19 12:14
Thanks for the additional images. There won't be another release until at
least next week.

**Comment by dashcambike** [comment] 2022-08-20 14:17
To confirm: do you think it could be out on the week of the 22nd, or 29th? Thank you!

**Comment by Chris-RH** [comment] 2022-08-22 06:41
I'll be able to ask one of the developers tomorrow, when he gets back from holiday.

**Comment by ModischFabrications** [comment] 2022-08-24 11:35
Same behaviour on Samsung Galaxy S22 (SM-S901B) with Android 12 / API 31

**Comment by Chris-RH** [comment] 2022-08-24 12:46
@dashcambike 
We are most likely looking at next week for the release. We are waiting on another team member coming back from holiday to do some more testing.

**Comment by MorrisRH** [comment] 2022-08-30 15:45
5.0.2 has just been released

**Comment by artoonie** [comment] 2022-08-31 18:04
Confirmed fixed on Android 13! Thanks Morris, Chris, & the whole team.

**Comment by arif69eee** [comment] 2022-09-19 04:36
Hi AVProMovieCapture Team,

Thanks for your continuous effort!

The bug has been fixed on most devices I think but still on some devices it is not fixed. We tested on devices as follows -

1. Xiaomi mi12: Fixed
2. Samsung Galaxy F22 (android v12): Fixed
3. OPPO K7x (android v12) : Not fixed

Would you please look into this and let us know what to do?

Thanks!

![image](https://user-images.githubusercontent.com/1552001/190950525-90cf5beb-7fc8-4e27-bf10-4cc33a24ee3d.jpg)

**Comment by MorrisRH** [comment] 2022-09-20 05:59
Hey @arif69eee, could we get the full logcat output for the device where it's not capturing correctly? We've added a lot of information to the logging so that we can try and figure out why things don't work for certain devices.
Could you also confirm you're using the latest release (5.0.3)?

**Comment by arif69eee** [comment] 2022-09-20 06:08
Hi @MorrisRH ,

Thanks for quick response!

The issue is occurring on our client's device. Is there any easy way that I can tell him to follow to get the logcat? (He is not a developer.)

Thanks!

**Comment by MorrisRH** [comment] 2022-09-20 07:37
We have a bit of documentation on how to capture logcat (available [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/platform-android.html#collecting-logcat-output)) but it is still slightly technical.

The Oppo K7x uses a Mali G57 GPU and we do have a fix coming in 5.0.4 for this issue with devices using the Mali G72 GPU so it could well be that the next release resolves this for you.

**Comment by arif69eee** [comment] 2022-09-20 08:20
OK, thanks @MorrisRH :) . Really appreciate your hard work!

**Comment by MorrisRH** [comment] 2022-09-20 09:08
Hopefully later today but sometime this week if not.

**Comment by arif69eee** [comment] 2022-09-20 09:10
Thanks @MorrisRH :)

**Closed** 2022-09-20 09:10 UTC
Labels: Bug 🐛, fixed, Android, High :fire_engine:
