### ISSUE TITLE
ProRes 4444 renders using Capture From Camera appear pixelated and glitchy on transparent areas 

### ISSUE THREAD

**Issue by visualmusicdesign** [RenderHeads/UnityPlugin-AVProMovieCapture#299] opened 2023-07-10 23:44 UTC
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
ProRes 4444 renders using Capture From Camera appear pixelated and glitchy on transparent areas 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.24f1
 - AVPro Movie Capture version: 5.1.7
 - Operating system version:  MacOS 13.2 - M1 Pro 2021 MacBook Pro - Apple Silicon Build / Editor 
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): 1920x1080, 30 FPS, Apple ProRes 4444

**To Reproduce**
1. Set up a scene with transparent graphical components over an empty background, and Camera clear flags set to Solid Color - 0 alpha
2. Record a clip using CaptureFromCamera using Apple ProRes 4444 Codec
3. Open the rendered video in Quicktime or Final Cut - see blocky glitches over transparent sections of video.  

**Logs**
N/A

**Videos**
https://www.dropbox.com/s/18edpe172lz6zr9/Transparent%20Glitches.mov

**Comment by MorrisRH** [comment] 2023-07-11 08:34
Can I get some more details about how your project/scene is setup?
- Are you using URP or HDRP?
- Which colourspace are you using?
- What is the target render texture format for the camera?
- What are you rendering into the alpha channel? Just masking or are there gradients, etc.?

**Comment by visualmusicdesign** [comment] 2023-07-11 16:46
I tested with the particle effects off - the issue is still present.

When I reduce the opacity of the falling bars so that it is below 50%, the issue then happens there as well, as well as with another "lights" layer.

I will try to test with the PNG sequence as soon as I have time.  I will note - the issue is not visible when the files are opened in VLC media player, or through a browser window playback.  The issue seems to be primarily with playback through Quicktime and Final Cut.

I'm sorry this isn't easily replicable.  Here is the information you requested in the previous comment:

1.  Using URP
2.  Using Gamma Color Space

3.  How do I tell what render texture format I am using for the camera?  Is this set through CaptureFromCamera before recording?  I could easily see changing this fixing the issue.

4. I am not manually rendering anything into the alpha channel - I'm just setting up the scene with GameObjects and materials, and then using the CaptureFromCamera component to capture the scene.  Some of the objects do have custom shaders, but they have a straightforward approach to calculating the alpha value for the game object.  There is no stenciling, sprite masking or other complexity of that kind occurring with the alpha.

**Comment by MorrisRH** [comment] 2023-07-12 09:46
I've setup a URP scene but still not able to reproduce this. Worth noting that enabling post-processing on the camera totally wipes the alpha channel though.

With URP the camera is going to be rendering to an FP16 render target. You can create your own render texture with an 8bit format (RGBA32) and assign it to the camera you're capturing from. This would show that the issue is a result of using a FP16 render target with whatever effects you're applying.

My guess is that the values being written to the render target are HDR and therefore some of them fall outside of the standard 0-1 range.

If you capture using the HEVC codec do you still see the blocks?

Are you able to provide a reproducible test scene? (If so please send it to unitysupport@renderheads.com)

**Comment by Chris-RH** [comment] 2023-07-18 10:56
Any further info @visualmusicdesign ?

**Comment by visualmusicdesign** [comment] 2023-07-18 16:25
Thank you for the follow up!

I have had a large amount of other urgent development - and this seems like this testing going to take a dedicated half day or day to work through... hoping to have time later today or tomorrow to thoroughly test.

Thank you for the suggestions, and I will follow up with my results and a test scene if necessary within 48-72 hours.

**Comment by visualmusicdesign** [comment] 2023-07-19 17:53
> Any further info @visualmusicdesign ?

It looks like this was a shader issue on my end.  

I was using a Blend One One additive shader, which can seem to ignore the alpha channel.  A color was being returned from the shader that only had RGB values set - the alpha channel was left uninitialized.  For whatever reason, this displayed fine in Unity, release builds, and opaque renders, so it never got caught.

Setting the alpha value for the color returned by that shader unsurprisingly seems to fix the issue...

Sorry for taking your time with this.  Your instinct was right!

Thank you

**Comment by Chris-RH** [comment] 2023-07-20 08:13
Awesome, thanks for letting us know :)

**Closed by Chris-RH** 2023-07-20 08:13 UTC
Labels: macOS
