### ISSUE TITLE
fps drops while recording

### ISSUE THREAD

**Issue by haqqi-zk** [RenderHeads/UnityPlugin-AVProMovieCapture#272] opened 2023-03-30 08:58 UTC
hello i want to ask if fps dropping almost by half while recording is an issue or not?
ex my scene run on 70 - 115 fps
but when it starts recording the fps drop between 40 - 75 fps

**Comment by Chris-RH** [comment] 2023-03-30 10:49
Please fill in a full bug report form

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
A clear and concise description of what the bug is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Movie Capture version: 
 - Operating system version: 
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2023-04-06 12:23
Closing due to lack of reply

**Closed by Chris-RH** 2023-04-06 12:23 UTC
Labels: Need more info
