### ISSUE TITLE
can't save to Application.persistentDataPath on iOS

### ISSUE THREAD

**Issue by mitkaw** [RenderHeads/UnityPlugin-AVProMovieCapture#23] opened 2019-11-21 14:17 UTC
Hello.
I can't save mp4 to Application.persistentDataPath on iOS.
MacOS is no problem using the same scene.
Could you please give me some advice?

mac:10.15.1
unity:2018.3.12f1
↓
device:iPhone 11 pro
os:13.2.2

Best regards.

**Comment by MorrisRH** [comment] 2019-12-03 16:45
Resolved via email, caused by conflict with another plugin.

**Closed by MorrisRH** 2019-12-03 16:45 UTC
